// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.API.Data;

#nullable disable

namespace TaskManagement.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260503093255_UpdateSeedDataFinal")]
    partial class UpdateSeedDataFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.API.Models.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StatusId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.TaskStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("TaskStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusName = "To Do"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusName = "In Progress"
                        },
                        new
                        {
                            StatusId = 3,
                            StatusName = "Completed"
                        },
                        new
                        {
                            StatusId = 4,
                            StatusName = "Overdue"
                        });
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 43, 395, DateTimeKind.Local).AddTicks(8776),
                            Email = "admin1@task.com",
                            FullName = "Admin One",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$i4CsdatACSA5qUHGLfUAreXQSdNS5lspvbXxAM0OACDWd3jQjhSua",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 43, 716, DateTimeKind.Local).AddTicks(1350),
                            Email = "admin2@task.com",
                            FullName = "Admin Two",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$StoFHPynkkO4/HBJrMtcheZxfPSgNN1c36oYa8.MUQZz81LZM/jr.",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 44, 21, DateTimeKind.Local).AddTicks(5582),
                            Email = "manager1@task.com",
                            FullName = "Manager 1",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$uZxa.VM1vibCo0nLBAVZBe7ZsOnrAYQZO4OZmtMPHEelU1wPuJ/iK",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 44, 332, DateTimeKind.Local).AddTicks(9032),
                            Email = "manager2@task.com",
                            FullName = "Manager 2",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$JedbqFYrW3X3Cy8CoXwCSenomUQd57byd/dbkKUDt7tQk5OgExkCK",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 44, 645, DateTimeKind.Local).AddTicks(6986),
                            Email = "manager3@task.com",
                            FullName = "Manager 3",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$SNC1jhiekkDUVgG8l/ulT.YQosp/Z48CnBT1u9nCBgsC8idBsRzZa",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 44, 941, DateTimeKind.Local).AddTicks(2564),
                            Email = "manager4@task.com",
                            FullName = "Manager 4",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$TRqYvd/eYx0izyRyTIOor.NlKiZNWbYGX.bKhM/IwqDz8CjM3VTAC",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 45, 242, DateTimeKind.Local).AddTicks(8116),
                            Email = "manager5@task.com",
                            FullName = "Manager 5",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$53Itim/EtYkAHCxtntGfFeaEb25x19Pum8RfGsyX/FAU2ftd/cJcu",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 45, 553, DateTimeKind.Local).AddTicks(6667),
                            Email = "employee1@task.com",
                            FullName = "Employee 1",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$tlcJFpn0apgzsM2Di1mo2OBNwokG3trreitgbtT9B53wWesEvQV0u",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 45, 854, DateTimeKind.Local).AddTicks(7487),
                            Email = "employee2@task.com",
                            FullName = "Employee 2",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$LxhFh0L7D0bmq6y0P8htjeghoKCMy3oWFgAlf7oUZf4ZAsdshY6lu",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 46, 144, DateTimeKind.Local).AddTicks(1611),
                            Email = "employee3@task.com",
                            FullName = "Employee 3",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$nUlTot1GoIX4oScKpwnzwObuJNcxUqi8BGIzRHDjtKpbbDW5Lu5FW",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 11,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 46, 418, DateTimeKind.Local).AddTicks(5405),
                            Email = "employee4@task.com",
                            FullName = "Employee 4",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$Am3O7kay/4KRwFqCg7Iv8.FZo7hZ37ku6kMmet74giGuoOq9KeiAa",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 12,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 46, 700, DateTimeKind.Local).AddTicks(5686),
                            Email = "employee5@task.com",
                            FullName = "Employee 5",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$N/d7ma.KbF8BVsEgZ1wyqOxZZ3hT/pL6XHFShbcmlhAIJVxn0A7KK",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 13,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 46, 955, DateTimeKind.Local).AddTicks(9967),
                            Email = "employee6@task.com",
                            FullName = "Employee 6",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$GmNeWfmkiVJltVAJJ5ay3.4kCyKyr6YEGKAyq297ajcCPTOEHiaWe",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 14,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 47, 261, DateTimeKind.Local).AddTicks(7667),
                            Email = "employee7@task.com",
                            FullName = "Employee 7",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$nKdfss/KSPbxWG1nTaPjb.9bvMRQXnaBXxkBjQFc5U.WECmhqYH5W",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 15,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 47, 785, DateTimeKind.Local).AddTicks(5394),
                            Email = "employee8@task.com",
                            FullName = "Employee 8",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$ouLXSWrfmJlRs8kUi4OJtuWv7T0rfVfhX7ZQiHcQDwTj4D6d8y/NS",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 16,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 48, 71, DateTimeKind.Local).AddTicks(5113),
                            Email = "employee9@task.com",
                            FullName = "Employee 9",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$uQ.0PpF5J/xLUL04ZXccueExelH5ENYtGENiW3uYLNm..o7D/xrkW",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 17,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 48, 387, DateTimeKind.Local).AddTicks(6832),
                            Email = "employee10@task.com",
                            FullName = "Employee 10",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$7RsB9QSCLqIkWgoC0UthM.At1oEVrm9vttDxlfaleMy8ow7d9TBYK",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 18,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 48, 695, DateTimeKind.Local).AddTicks(8996),
                            Email = "employee11@task.com",
                            FullName = "Employee 11",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$Rscdm7/YkCuht7JnI4YM4O0FVtXgEXdq5i24e.yjibX3t.U.kPvRu",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 19,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 48, 993, DateTimeKind.Local).AddTicks(8432),
                            Email = "employee12@task.com",
                            FullName = "Employee 12",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$ugsC9vY0ybKfThBGUa.2SeDo41XOTWpmPWlby6SDJE/epxXKONubi",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 20,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 49, 283, DateTimeKind.Local).AddTicks(2517),
                            Email = "employee13@task.com",
                            FullName = "Employee 13",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$LW5mJ/893NczwrqohQQq7uJii0Qj5bntNswP9FZAh/.hbtjKTBEF.",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 21,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 49, 586, DateTimeKind.Local).AddTicks(6274),
                            Email = "employee14@task.com",
                            FullName = "Employee 14",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$dtcOQbFGyl1GhnTz2ntu1umocQ4GN.swDaQmjxFsHIsNV4SDOA0zi",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 22,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 49, 889, DateTimeKind.Local).AddTicks(9573),
                            Email = "employee15@task.com",
                            FullName = "Employee 15",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$wN/gYqnBUIFU4bFw2fKWYOdgNJ.Wk2dm9noKpBZCqdlcrkQ/lbb/a",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 23,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 50, 177, DateTimeKind.Local).AddTicks(4193),
                            Email = "employee16@task.com",
                            FullName = "Employee 16",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$t.T0SlxxElQb44ZrdrOfWuYOG5ftqBuHewwUqiuPah/SFdYxZTBgW",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 24,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 50, 492, DateTimeKind.Local).AddTicks(5820),
                            Email = "employee17@task.com",
                            FullName = "Employee 17",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$XXntqtC4wW.CzHI8I1rkzO3Rjl2DXBZutYJhG4uHLbKFiME/Jhxzi",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 25,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 50, 784, DateTimeKind.Local).AddTicks(4455),
                            Email = "employee18@task.com",
                            FullName = "Employee 18",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$pAwFDpu8OlGsm7cd6WNVA.2aJeCKBeTz37SCfGRvhPEiEpBaVJW96",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 26,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 51, 66, DateTimeKind.Local).AddTicks(6924),
                            Email = "employee19@task.com",
                            FullName = "Employee 19",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$XFug77JieJuvyRSHemReuOyVxp892IGb22Q8dyhRY3.dqixrQTI56",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 27,
                            CreatedAt = new DateTime(2026, 5, 3, 16, 32, 51, 379, DateTimeKind.Local).AddTicks(6901),
                            Email = "employee20@task.com",
                            FullName = "Employee 20",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$bhFUz3AXsjT0ibulnPF2VudBtgT.9PhXn0BBDpTgiAcw4cpzTey7S",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.Notification", b =>
                {
                    b.HasOne("TaskManagement.API.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.Project", b =>
                {
                    b.HasOne("TaskManagement.API.Models.Entities.User", "Creator")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.ProjectMember", b =>
                {
                    b.HasOne("TaskManagement.API.Models.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.API.Models.Entities.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.Task", b =>
                {
                    b.HasOne("TaskManagement.API.Models.Entities.User", "Assignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskManagement.API.Models.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.API.Models.Entities.TaskStatus", "Status")
                        .WithMany("Tasks")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Project");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.User", b =>
                {
                    b.HasOne("TaskManagement.API.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.Project", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.TaskStatus", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskManagement.API.Models.Entities.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedProjects");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
